// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KH2FM.Model;
//
//    var worlds = Worlds.FromJson(jsonString);

namespace MultiPresence.Models.KH2
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Worlds
    {
        [JsonProperty("Worlds", NullValueHandling = NullValueHandling.Ignore)]
        public World[] ReadWorld { get; set; }
    }

    public partial class World
    {
        [JsonProperty("ID", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Image", NullValueHandling = NullValueHandling.Ignore)]
        public string Image { get; set; }

        [JsonProperty("Rooms", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Rooms { get; set; }
    }

    public partial class Worlds
    {
        public static Worlds FromJson(string json) => JsonConvert.DeserializeObject<Worlds>(json, MultiPresence.Models.KH2.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Worlds self) => JsonConvert.SerializeObject(self, MultiPresence.Models.KH2.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
